### ISSUE TITLE
Another linux impl

### ISSUE THREAD

**Issue by dpnova** [coinscrow/minerstat-linux#2]
Because I couldn't debug the issue in #1 I tried implementing something myself: https://github.com/dpnova/pynerstat

I've found that I'm having similar issues... I think the claymore-eth log output from my machine isn't being recognised... is that something you could look into?

**Comment by xstead** [comment]
Just a simple script for keep alive ethminer.
https://github.com/xstead/ethereum-miner-monitor

**Comment by coinscrow** [comment]
These all fixed now, we are out of Alpha/Beta.
