### ISSUE TITLE
Nvidia gpu monitoring is broken

### ISSUE THREAD

**Issue by carlosmenezes** [coinscrow/minerstat-linux#3]
The monitoring client is not sending gpu stats to minerstat servers making worker permanently offline, after some debugging I've found the problem.

It seems nvidia-smi returns more than 1 line as result of `nvidia-smi --query-gpu=count --format=csv,noheader`, Example:

```
$ nvidia-smi --query-gpu=count --format=csv,noheader
2
2
```

Changing monitor.js:71 to `gpunum = exec("nvidia-smi --query-gpu=count --format=csv,noheader | tail -n1",`
fixes the problem.

Sorry my bad English, hope it helps!

**Comment by coinscrow** [comment]
Thank you! 

I commit your suggestion, hardware monitor still need work on Server side.
Within 48 hour i'm going to apply nvidia hw data over the API. 

I keep this open until resolved.

**Comment by coinscrow** [comment]
Resolved. Linux Nvidia HW monitor data is now on our API.
